services:
  web:
    container_name: web
    build: .
    volumes:
      - ./src:/var/code/src
    ports:
      - '8000:8000'
    networks: 
      - backend

  db:
    container_name: db
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localdebug
      MYSQL_DATABASE: core_db
    ports:
      - '3308:3306'
    volumes:
      - ./database:/var/lib/mysql
    networks: 
      - backend

networks:
  backend:

volumes:
  app:
  database: